### ISSUE TITLE
Correcciones TP2

### ISSUE THREAD

**Issue by mbuchwald** [JuaniFIUBA/TP2-TDA#1]
Hola. Les paso por acá las correcciones del TP. 
* La ecuación de recurrencia tiene una función (recurrente) $Ganancia[i, j]$ que no está definida en ningún lado... ¿no debería ser esta la definición de $Ganancia[i][j]$ y luego $Opt(i)$ ser simplemente el máximo de ese día dado todos los posibles $j$? O lo que fuera que está faltando. 
* No se analiza la complejidad de la reconstrucción, la cual es interesante. Dependiendo de la implementación puede justamente variar en función de los valores de $e_i$ y $s_i$ (no varía la complejidad total pero si la de esta parte). 
* Hacen un gráfico que muestra potencial variaciones de según los valores de los parámetros, y no sacan ninguna conclusión al respecto. 
* Muy importante: no tengo forma de ejecutar el programa. Quiero validar con una prueba que tengo yo y no hay algo que ejecutar. 

Les pido que reentreguen si o si lo que me refiero a lo último. Se tiene que poder ejecutar de alguna forma. Lo del primer punto es también importante, pero tomo la decisión de dejarlo opcional. 
Saludos

**Comment by JuaniFIUBA** [comment]
Buenas profe, ahí subimos las correcciones, saludos cordiales.

**Comment by mbuchwald** [comment]
Dejo por acá la re-corrección para que quede todo junto: 
* En la ecuación de recurrencia ponen $OPT(i) = max(Ganancia[i][j]) \forall i, j)$. Entonces eso sería el óptimo, no el óptimo de $i$. En todo caso habría que sacar i de allí (me refiero adentro del $forall$). De paso, podrían tranquilamente hacer que la otra ecuación dependa de esta, ya que está definida. 

El resto está visto y validado. 
Con esto, cerramos el tp con 8.
